### ISSUE TITLE
swaggerエラー

### ISSUE THREAD

**Issue by yakult1995** [SUfest/fest1#16]
@k-nasa 
* GET `/articles`の`last_article_id`ってどこから取得出来るんやっけ？

**Comment by k-nasa** [comment]
ページング用ですね。クライアントから、クエリパラメーターとして最後に取得したarticle_idを送ってもらう予定です。

**Comment by yakult1995** [comment]
URLパラメータとして取得する？

**Comment by k-nasa** [comment]
そうです

**Comment by yakult1995** [comment]
swagger修正しときまする

**Comment by yakult1995** [comment]
これ、俺修正したっけ？笑

**Comment by k-nasa** [comment]
https://github.com/SUfest/fest1/blob/master/webapp/doc/swagger.yml#L72
されてますね
