### ISSUE TITLE
migrationツールの選定、環境構築 + migration

### ISSUE THREAD

**Issue by k-nasa** [SUfest/fest1#3]
APIの概要が決まったらmigrationする
DBはmysqlを使う想定

**Comment by yakult1995** [comment]
Golangならgooseでいいんちゃいます？

**Comment by k-nasa** [comment]
https://github.com/rubenv/sql-migrate
これ使ってみようかと思ってます。
gooseとの違いはあまり分かってませんがGitHubのスター数で決めました。

**Comment by yakult1995** [comment]
いいよ◯

**Comment by k-nasa** [comment]
取り敢えず今日中にmigrationをしたいお気持ちです。

**Comment by yakult1995** [comment]
🥇

**Comment by yakult1995** [comment]
db設計も今日中に終わらせるってこと？

**Comment by k-nasa** [comment]
そのつもりでしたがモンハンで忙しくなってしまったのでツールだけにしときます。
https://github.com/SUfest/fest1/pull/8
